# Generated by Django 3.2.5 on 2022-01-09 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('grade', models.CharField(default='', max_length=5, verbose_name='Grade')),
                ('school', models.CharField(default='', max_length=20, verbose_name='School')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='e-mail')),
                ('parent_name', models.CharField(default='', max_length=50, verbose_name='Middle Name')),
                ('contact_number', models.CharField(default='', max_length=12, verbose_name='Contact Number')),
                ('alternate_contact_number', models.CharField(default='', max_length=12, verbose_name='Alternate Contact Number')),
                ('enquiry_source', models.CharField(default='', max_length=50, verbose_name='Source of Enquiry')),
                ('enquiry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Enquiry')),
            ],
            options={
                'verbose_name': 'Student Data',
                'verbose_name_plural': "Student Data's",
            },
        ),
    ]
