# Generated by Django 3.2.5 on 2022-01-09 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20220109_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alternate_contact_number',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\d{8,8}$')], verbose_name='Alternate Contact Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\d{8,8}$')], verbose_name='Contact Number'),
        ),
    ]
