# Generated by Django 3.2.5 on 2022-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20220109_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alternate_contact_number',
            field=models.CharField(default='', max_length=12, verbose_name='Alternate Contact Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(default='', max_length=12, verbose_name='Contact Number'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('name', 'grade', 'contact_number')},
        ),
    ]
